openapi: 3.0.0
info:
  title: MYSQL FLASK API
  description: API for interacting with the database
  version: 1.0.0
servers:
  - url: https://3245-filippopietron-mysqlapi-kqukjbo15hh.ws-eu116.gitpod.io
paths:
  /api/tables:
    get:
      summary: Get all tables in the database
      responses:
        '200':
          description: A list of tables
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /api/tables/{table_name}:
    get:
      summary: Get data from a specific table
      parameters:
        - name: table_name
          in: path
          required: true
          description: The name of the table to retrieve data from
          schema:
            type: string
      responses:
        '200':
          description: Data from the table
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    categoria:
                      type: string
                    id:
                      type: number
                    immagine:
                      type: string
                    nome:
                      type: string
                    prezzo:
                      type: string
                    quantita:
                      type: number
    put:
      summary: Update a row in a specific table
      parameters:
        - name: table_name
          in: path
          required: true
          description: The name of the table where the row is located
          schema:
            type: string
      requestBody:
        description: Data to update in the table
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: number
                  description: Primary key of the row to update
                categoria:
                  type: string
                  description: Updated category
                immagine:
                  type: string
                  description: Updated image URL
                nome:
                  type: string
                  description: Updated name
                prezzo:
                  type: string
                  description: Updated price
                quantita:
                  type: number
                  description: Updated quantity
      responses:
        '200':
          description: Row updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Row updated successfully
    delete:
      summary: Delete a row from a specific table
      parameters:
        - name: table_name
          in: path
          required: true
          description: The name of the table to delete the row from
          schema:
            type: string
      requestBody:
        description: Row to delete from the table
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: number
                  description: Primary key of the row to delete
      responses:
        '200':
          description: Row deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Row deleted successfully
